<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'User' => 'Пользователь',
  'Balance' => 'Баланс',
  'Role' => 'Роль',
  'Amount' => 'Сумма',
  'Created' => 'Создан',
  'Avg of Params' => 'Среднее',
  'Type' => 'Тип',
  'Comment' => 'Комментарий',
  'Statistics' => 'Статистика',

  'Admin' => 'Админ',
  'Customer' => 'Заказчик',
  'Worker' => 'Исполнитель',
  'Unknown' => 'неизвестен',
  
  'Charge the worker account' => 'Пополнение счета исполнителя',
  'Debit the worker account' => 'Снятие со счета исполнителя',
  'Charge the customer account' => 'Пополнение счета заказчика',
  'Debit the customer account' => 'Снятие со счета заказчика',
  
);
