<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Name' => 'Название товара',
  'Param1' => 'Параметр 1',
  'Param2' => 'Параметр 2',
  'Param3' => 'Параметр 3',
  'Sum of Params' => 'Сумма',
  'Avg of Params' => 'Среднее',
);
